### ISSUE TITLE
requires boost for regular make

### ISSUE THREAD

**Issue by jeremybernstein** [HBPVIS/Servus#60]
As of this commit. Since we're in C++11, why not just use basic_regex<char>?

https://github.com/HBPVIS/Servus/commit/229a659bc3febff3f37754a914354c5ea9702591

**Comment by tribal-tec** [comment]
I think it's related to not having a regex impl for gcc <= 4.8: http://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions

@rdumusc correct me if I'm wrong and if there's another reason for choosing boost.regex here.

**Comment by jeremybernstein** [comment]
GCC <= 4.8 isn't C++11 feature-complete anyway. GCC 4.8.1 is the first version which is: https://gcc.gnu.org/projects/cxx-status.html . It might be (IMO) better to put the boost stuff behind the SERVUS_USE_CXX03 ifdef and defining that automatically if the GCC version < 4.8.1.

**Comment by rdumusc** [comment]
correct, when I last checked std::regex support was lacking in most implementations of the standard, but we should use it if in fact possible.
Otherwise, I agree that boost::regex should be an optional dependency. It is only used for printing a compatibility warning for the URI parsing, which I am not sure is even required any longer.

**Comment by rdumusc** [comment]
Yes, implementation of std::regex_match comes with gcc 4.9 only (http://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions)
Added compiler guards to not include the warning when compiling without boost:
https://github.com/HBPVIS/Servus/pull/61
